# Generated by Django 2.0.7 on 2019-03-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=150)),
                ('price', models.FloatField(verbose_name='цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('release_date', models.DateField(verbose_name='Релиз')),
                ('lte_exists', models.BooleanField(verbose_name='LTE')),
            ],
        ),
    ]
