# Generated by Django 2.0.7 on 2019-03-29 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=40, verbose_name='model_name')),
                ('brand', models.CharField(max_length=40, verbose_name='brand')),
                ('screen', models.CharField(max_length=5, verbose_name='screen')),
                ('processor', models.CharField(max_length=40, verbose_name='processor')),
                ('camera', models.BooleanField(default=True, verbose_name='camera')),
                ('battery', models.IntegerField(default=100, verbose_name='battery')),
                ('memory', models.IntegerField(default=0, verbose_name='memory')),
            ],
        ),
        migrations.CreateModel(
            name='Asus',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('teleport', models.BooleanField(default=False, verbose_name='teleport')),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='Nokia',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('scan_eye', models.BooleanField(default=False, verbose_name='scan_eye')),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='Xiaomi',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('scan_finger', models.BooleanField(default=False, verbose_name='scan_finger')),
            ],
            bases=('phones.phone',),
        ),
    ]
