# Generated by Django 2.0.7 on 2018-12-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nokia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nokia', max_length=50, verbose_name='name')),
                ('scan_eye', models.BooleanField(default=False, verbose_name='scan_eye')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=40, verbose_name='model_name')),
                ('screen', models.CharField(max_length=5, verbose_name='screen')),
                ('camera', models.BooleanField(default=True, verbose_name='camera')),
                ('battery', models.IntegerField(default=100, verbose_name='battery')),
                ('memory', models.IntegerField(default=0, verbose_name='memory')),
            ],
        ),
        migrations.CreateModel(
            name='Xiomi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Xiomi', max_length=50, verbose_name='name')),
                ('scan_finger', models.BooleanField(default=False, verbose_name='scan_finger')),
                ('parametrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Phone')),
            ],
        ),
        migrations.AddField(
            model_name='nokia',
            name='parametrs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Phone'),
        ),
    ]
