# Generated by Django 2.0.7 on 2019-04-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Тема статьи')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_topic',
            field=models.ManyToManyField(to='articles.ArticleTopic', verbose_name='Тема статьи'),
        ),
    ]
